@startuml

[*] --> signup
signup --> usecase
usecase: add use types
usecase: babysitter (multiselect)
usecase: parent (multiselect)
usecase --> schedule
schedule: select schedule
schedule --> details
' hire sitter
details --> hire : sitter
hire: background check sitter 
hire: add to sitter list
hire --> [*]
' request sitter
details --> request
request: notify available sitters
request --> job
job: parent
job: distance
job: time slot
job: accept (sitter, select)
job: deny (sitter, select)
' accept position
job --> confirmation : sitter 
confirmation: block out availability (sitter)
confirmation: address
confirmation: time slot
confirmation --> [*]
' confirm appointment
job --> appointment : parent
appointment: charge parent
appointment: time slot
appointment: sitter
appointment --> [*] : parent
' pay sitter 
appointment --> payroll : timer
payroll: pay sitters
payroll --> fulfilled
' complete job
fulfilled --> support
support: online text chat (sends text)
support: fill out form (sends email)
support: text or call <phone #>
support: email at <email>
support --> [*]
' remind sitter
appointment --> reminder : sitter
reminder: 1.5 hours before
reminder: text or call <phone #>
reminder --> [*]

state schedule {
  [*] --> scheduled
  ' request babysitter
  [*] --> appointments : parent
  appointments: for parents (select)
  appointments --> scheduled
  ' babysit
  scheduled --> availability : sitter
  availability: for sitters (select)
  availability --> [*]
  scheduled --> [*]
}

state details {
  [*] --> account
  details: account
  account: full name (required)
  account --> contact
  contact: phone # (required)
  contact: email (required)
  contact: SSN (babysitter)
  contact --> address
  address: street (required)
  address: radius (sitter)
  address --> payment
  payment --> confirm
  confirm: sumarize details
  confirm --> [*]
}

state payment {
  [*] --> method
  method: credit card (select)
  method: venmo (select)
  method: paypal (select)
  method --> verify 
  verify: verify pay method
  verify --> [*]
}

@enduml

